services:
  app:
    build: .
    container_name: ems_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - .env 

  mysql:
    image: mysql:8.3
    container_name: ems_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DSN}
      MYSQL_DATABASE: ems
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ems_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
