services:
  app:
    build: .
    container_name: ems_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      ENV: production
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASS: ${ADMIN_PASS}
      MYSQL_DSN: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_ADDR})/${MYSQL_DATABASE}?parseTime=true
      REDIS_ADDR: ${REDIS_ADDR}

  mysql:
    image: mysql:8.0
    container_name: ems_mysql
    restart: always
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: ems_redis

volumes:
  mysql_data:
